### ISSUE TITLE
WeAct Studio WeiXing Store on AliExpress

### ISSUE THREAD

**Issue by fivdi** [WeActTC/MiniF4-STM32F4x1#16]
Are the products available at the [WeAct Studio WeiXing Store](https://aliexpress.com/store/910567080) on AliExpress original WeAct Studio products?

**Comment by DavidCampbellTech** [comment]
If you look at the react GitHub page, they list “safe” shops to buy from:

https://github.com/WeActTC/MiniF4-STM32F4x1

**Comment by WeActTC** [comment]
Yes, our official store

**Comment by fivdi** [comment]
Excellent. Maybe you could add it to the AliExpress legal purchase list [here](https://github.com/WeActTC/MiniF4-STM32F4x1#aliexpress-legal-purchase-link).

**Comment by WeActTC** [comment]
OK
