### ISSUE TITLE
Official AliExpress store?

### ISSUE THREAD

**Issue by linuxtim** [WeActTC/MiniF4-STM32F4x1#21]
Hello,

I'm think this is your new AliExpress store?  https://www.aliexpress.com/store/910567080  If-so, could it be put into the README.md?

Thanks,

Tim.

**Comment by fivdi** [comment]
Duplicate of #16. See also #19.

**Comment by linuxtim** [comment]
Thanks! Possibly the items in README.md could be numbered list (like other sections?).

**Comment by WeActTC** [comment]
ok

**Comment by zoggn** [comment]
> ok

You can close this issue i think.

**Comment by linuxtim** [comment]
Looks good, thanks.
